# Generated by Django 4.1.2 on 2022-10-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
