# Generated by Django 4.1.2 on 2022-10-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_alter_list_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="description",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
